---
- hosts: master
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: Add group "hadoop"
      group:
        name: hadoop

    - name: Add user "hadoop"
      user:
        name: hadoop
        group: hadoop
        home: /home/hadoop
        shell: /bin/bash
        password: "{{ hadoop_user_passwd }}"

    - name: Add env vars to .profile
      blockinfile:
        dest: /home/hadoop/.profile
        marker: "# {mark} Added env vars"
        block: |
          export HADOOP_HOME={{ hadoop_dir }}/hadoop-{{ hadoop_version }}
          export HADOOP_MAPRED_HOME=$HADOOP_HOME
          export PATH=$PATH:$HADOOP_HOME/bin
          export HADOOP_EXAMPLES=$HADOOP_HOME/share/hadoop/mapreduce/hadoop-mapreduce-examples-{{ hadoop_version }}.jar
          export RGen='hadoop jar /vagrant/target/rgen-1.0-SNAPSHOT-jar-with-dependencies.jar'
        backup: yes
        
- name: Java installation
  import_playbook: java.yml

- name: Hadoop installation and setup
  import_playbook: hadoop.yml
